name: Azure Resources Deletion

on:
  schedule:
    - cron: '0 0 * * *' # Schedule the job to run every day at midnight UTC
  workflow_dispatch:

jobs:
  delete_resources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        azcliversion: 'latest'

    - name: Delete Azure Resources
      run: |
        # Log in to Azure
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

        # Delete all resources in the subscription
        az resource delete --ids $(az resource list --query "[].id" --output tsv) --yes

        # Log out of Azure
        az logout
